version: "3.7"

services:
  proxy:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/base

  proxy-with-krb:
    image: brainsum/containerized-webserver:0.3.3-kerberos
    build:
      dockerfile: ./Dockerfile
      context: ./docker/kerberos
      args:
        BASE_IMAGE_TAG: 0.3.3
