version: "3.7"

services:
  proxy:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/base

  proxy-with-krb:
    image: brainsum/general-nginx-proxy:0.3.1-kerberos
    build:
      dockerfile: ./Dockerfile
      context: ./docker/kerberos
      args:
        BASE_IMAGE_TAG: 0.3.1
