#!/bin/bash

# @see: https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks

# The base tag should be latest or the tag.

baseTag=latest

if [[ ${SOURCE_BRANCH} =~ ^[0-9.]+$ ]]; then
    baseTag=${SOURCE_BRANCH}
fi;

docker build --build-arg BASE_IMAGE_TAG=${SOURCE_BRANCH} -t $IMAGE_NAME .
