#!/bin/bash

# @see: https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks

echo "Using base image tag: ${BASE_IMAGE_TAG}"
echo "Build tag: ${DOCKER_TAG}"

docker build --build-arg BASE_IMAGE_TAG=$BASE_IMAGE_TAG -t $IMAGE_NAME .
